image: node:6.9.4

pipelines:
  branches:
    master:
      - step:
          script:
            - npm install -g surge
            - npm install
            - npm run build
            - surge build todo.surge.sh